# Site settings
title: Andre Sugai
email: asugai@alum.mit.edu
description: Regional VP @ projekt202 - Enterpreneur
tagline: Brazil - Japan - Peru - USA
timezone: America/Chicago
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andresugai.com" # the base hostname & protocol for your site
permalink: /posts/:title

author: Andre Sugai
author_photo: http://gravatar.com/avatar/61b417f7e95fdfb1d9cfe4602e456be6?s=400
email: asugai@alum.mit.edu
github: asugai
repository: asugai.github.io
twitter: gymclothes
facebook: andresugai
linkedin: andresugai
disqus: andresugai

# Build settings
markdown: kramdown
highlighter: pygments
